# Kitty terminal configurations
enable_audio_bell no
window_padding_width 12
foreground white
background #2b2f33
background_opacity 0.92
selection_foreground white
selection_background #565656
font_family Maple Mono
